### ISSUE TITLE
Exception, when app without models is migrated

### ISSUE THREAD

**Issue by devoto13** [BertrandBordage/django-cachalot#26]
I get following exception, when try to run `./manage.py migrate`:

```
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 2358, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1778, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc) 
  File "manage.py", line 17, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/devoto13/.virtualenvs/backend/lib/python3.4/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/Users/devoto13/.virtualenvs/backend/lib/python3.4/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/devoto13/.virtualenvs/backend/lib/python3.4/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Users/devoto13/.virtualenvs/backend/lib/python3.4/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/Users/devoto13/.virtualenvs/backend/lib/python3.4/site-packages/django/core/management/commands/migrate.py", line 165, in handle
    emit_post_migrate_signal(created_models, self.verbosity, self.interactive, connection.alias)
  File "/Users/devoto13/.virtualenvs/backend/lib/python3.4/site-packages/django/core/management/sql.py", line 268, in emit_post_migrate_signal
    using=db)
  File "/Users/devoto13/.virtualenvs/backend/lib/python3.4/site-packages/django/dispatch/dispatcher.py", line 198, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/Users/devoto13/.virtualenvs/backend/lib/python3.4/site-packages/cachalot/monkey_patch.py", line 161, in _invalidate_on_migration
    invalidate_models(sender.get_models(), db_alias=kwargs['using'])
  File "/Users/devoto13/.virtualenvs/backend/lib/python3.4/site-packages/cachalot/api.py", line 66, in invalidate_models
    cache_alias, db_alias)
  File "/Users/devoto13/.virtualenvs/backend/lib/python3.4/site-packages/cachalot/api.py", line 47, in invalidate_tables
    _invalidate_table_cache_keys(cache, table_cache_keys)
  File "/Users/devoto13/.virtualenvs/backend/lib/python3.4/site-packages/cachalot/utils.py", line 133, in _invalidate_table_cache_keys
    cache.set_many(d, None)
  File "/Users/devoto13/.virtualenvs/backend/lib/python3.4/site-packages/redis_cache/backends/single.py", line 67, in set_many
    return self._set_many(self.master_client, new_data)
  File "/Users/devoto13/.virtualenvs/backend/lib/python3.4/site-packages/redis_cache/backends/base.py", line 315, in _set_many
    return client.mset(data)
  File "/Users/devoto13/.virtualenvs/backend/lib/python3.4/site-packages/redis/client.py", line 940, in mset
    return self.execute_command('MSET', *items)
  File "/Users/devoto13/.virtualenvs/backend/lib/python3.4/site-packages/redis/client.py", line 565, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/Users/devoto13/.virtualenvs/backend/lib/python3.4/site-packages/redis/client.py", line 577, in parse_response
    response = connection.read_response()
  File "/Users/devoto13/.virtualenvs/backend/lib/python3.4/site-packages/redis/connection.py", line 574, in read_response
    raise response
redis.exceptions.ResponseError: wrong number of arguments for 'mset' command
```

The problems seems to be in the `_invalidate_table_cache_keys()`, when it receives empty sequence as a second argument. And issues exists for all apps without models.

**Comment by BertrandBordage** [comment]
That’s right, it’ll be fixed soon ;)

**Comment by BertrandBordage** [comment]
Of course, in the meantime you can just comment `'cachalot',` in `INSTALLED_APPS`, run `./manage.py migrate`, uncomment it and run `./manage.py invalidate_cachalot`.

**Comment by devoto13** [comment]
No problems. I just downgraded to previous release until it's fixed.

**Comment by BertrandBordage** [comment]
This is the same issue as #28, you’re using django-redis-cache instead of django-redis.
