### ISSUE TITLE
AttributeError: 'Query' object has no attribute 'having'

### ISSUE THREAD

**Issue by catnapgames** [BertrandBordage/django-cachalot#43]
Hi, I'm trying to setup cachalot (1.1.0 installed with pip) with a Django site running Django 1.9 + SQLite and I get this error whenever I try to request a page:

Unhandled exception in thread started by <function wrapper at 0x10bbf7668>
Traceback (most recent call last):
  File "/Users/tomasandrle/Sites/SilverRocket/env/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/Users/tomasandrle/Sites/SilverRocket/env/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    self.check_migrations()
  File "/Users/tomasandrle/Sites/SilverRocket/env/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 163, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/Users/tomasandrle/Sites/SilverRocket/env/lib/python2.7/site-packages/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/Users/tomasandrle/Sites/SilverRocket/env/lib/python2.7/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/Users/tomasandrle/Sites/SilverRocket/env/lib/python2.7/site-packages/django/db/migrations/loader.py", line 176, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/Users/tomasandrle/Sites/SilverRocket/env/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 66, in applied_migrations
    return set(tuple(x) for x in self.migration_qs.values_list("app", "name"))
  File "/Users/tomasandrle/Sites/SilverRocket/env/lib/python2.7/site-packages/django/db/models/query.py", line 258, in __iter__
    self._fetch_all()
  File "/Users/tomasandrle/Sites/SilverRocket/env/lib/python2.7/site-packages/django/db/models/query.py", line 1074, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/Users/tomasandrle/Sites/SilverRocket/env/lib/python2.7/site-packages/django/db/models/query.py", line 128, in __iter__
    for row in compiler.results_iter():
  File "/Users/tomasandrle/Sites/SilverRocket/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 806, in results_iter
    results = self.execute_sql(MULTI)
  File "/Users/tomasandrle/Sites/SilverRocket/env/lib/python2.7/site-packages/cachalot/monkey_patch.py", line 29, in inner
    out = original(compiler, *args, **kwargs)
  File "/Users/tomasandrle/Sites/SilverRocket/env/lib/python2.7/site-packages/cachalot/monkey_patch.py", line 77, in inner
    table_cache_keys = _get_table_cache_keys(compiler)
  File "/Users/tomasandrle/Sites/SilverRocket/env/lib/python2.7/site-packages/cachalot/utils.py", line 147, in _get_table_cache_keys
    tables = _get_tables(compiler.query, db_alias)
  File "/Users/tomasandrle/Sites/SilverRocket/env/lib/python2.7/site-packages/cachalot/utils.py", line 128, in _get_tables
    + query.having.children)
AttributeError: 'Query' object has no attribute 'having'

what does this mean?

**Comment by BertrandBordage** [comment]
See #41.
