### ISSUE TITLE
invalidate_cachalot management command : BaseCommand.option_list is deprecated in Django 1.8 and removed in Django 1.10

### ISSUE THREAD

**Issue by ndanielsen** [BertrandBordage/django-cachalot#59]
>docker-compose -f dev.yml run django python manage.py invalidate_cachalot
Traceback (most recent call last):
  File "manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 208, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/local/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/local/lib/python3.5/site-packages/cachalot/management/commands/invalidate_cachalot.py", line 8, in <module>
    class Command(BaseCommand):
  File "/usr/local/lib/python3.5/site-packages/cachalot/management/commands/invalidate_cachalot.py", line 11, in Command
    option_list = BaseCommand.option_list + (
AttributeError: type object 'BaseCommand' has no attribute 'option_list'

**Comment by BertrandBordage** [comment]
Already fixed by 72596ac0b1692f1503e438e879378a00b0b8515b.

**Comment by ndanielsen** [comment]
Thanks!
